id: P002896
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:27:00.687365
source_metadata:
  id: bdr:W1KG12203
  title: རྫོགས་ཆེན་དགོན་པའི་སྨིན་གླིང་རྡོར་སེམས་ཀྱི་འདོན་ཆའི་སྐོར།
  author: ''
  volumes:
    e751cc28fa4c46be88228f5c34f0eafd:
      image_group_id: I1KG12298
      title: ''
      volume_number: 1
      total_pages: 250
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
