id: I4FCC2C46
legacy_id: P002896
ocr_import_info:
  bdrc_scan_id: W1KG12203
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T14:57:22'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:25:25.146014+00:00'
last_modified: 2022-08-31 11:25:33.878041
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12203
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12203
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫོགས་ཆེན་དགོན་པའི་སྨིན་གླིང་རྡོར་སེམས་ཀྱི་འདོན་ཆའི་སྐོར།
statistics:
  ocr_word_mean_confidence_index: 0.7633556585047994
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I1KG12298:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12298
      total_pages: 250
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12298.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7633556585047994
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
